version: '3.7'

services:
  regression:
    # image: python:3.11.5-alpine3.18
    image: mcr.microsoft.com/playwright/python:v1.39.0-jammy
    # build:
    #   context:
    #     dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command:
      - /bin/sh
      - -c
      - |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1_all.deb
        sudo dpkg -i allure_2.24.1-1_all.deb
        ls -la && pip install --upgrade pip && pip debug && pip install -r requirements.txt && pip install playwright && pytest -sv --alluredir=reports
    # command: /bin/sh -c "ls -la && pytest -sv --alluredir=reports"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}